# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CheckSSL

on:
  push:
    branches:
      - master
  schedule: 
       - cron: '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout default branch to .
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout gh-pages branch to ./public
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: public

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyOpenSSL
        
    - name: run tasks
      env:
        MY_DOMAINS: ${{ secrets.MY_DOMAINS }}
      run: |
        python check_ssl.py
        mv -f result.json ./public/result.json

    - name: commit
      id: commit
      run: |
        cd public
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
        git add .
        git commit -m "update by action_bot"
        git push
      continue-on-error: true
